[workspace]
members = [
    "sirin",
    "sirin-macros",
    "sirin-shared",
    "bmp3",
    "dev-csr",
    "dev-csr-macro",
    "h3lis",
    "lsm6dso-spi",
    "rfm9",
    "spi-handle",
    "w25qx",
    "sirin-c",
    "examples/imu-test",
    "examples/bare",
    "examples/h3lis-test",
    "examples/main",
    "examples/airbrakes-test",
    "examples/nosecone-ebay",
    "examples/dongle",
    "examples/airbrakes"
]
resolver = "2"

[profile.dev]
debug = true
lto = true
opt-level = "z"
incremental = true

[profile.release]
debug = false
lto = true
opt-level = "z"
incremental = true
