[package]
name = "sirin"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Code for Sirin"
repository = "https://github.com/Nautki/sirin"

# Own the libs one crate at a time
[lib]
test = false
bench = false

[features]
s1 = []

[dependencies]
sirin-macros = { path = "../sirin-macros" }
cortex-m-rt = "0.7.3"
embassy-executor = { git = "https://github.com/embassy-rs/embassy", features = ["arch-cortex-m", "executor-thread", "defmt"] }
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy", features = [ "stm32h743ii" ]}
embassy-sync = { git = "https://github.com/embassy-rs/embassy" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy" }
embassy-usb = { git = "https://github.com/embassy-rs/embassy" }
embassy-usb-driver = { git = "https://github.com/embassy-rs/embassy" }
static_cell = "^2.1.0"
async-trait = "0.1.74"
enum-display-derive = "0.1.1"
embedded-hal-async = "1.0.0"
unhygienic2 = "0.1.0"
derive-new = "0.6.0"
spi-handle = { version = "0.1.1", path = "../spi-handle" }
bmp3 = { version = "0.1.1", path = "../bmp3" }
defmt = "0.3.8"
rfm9 = { version = "0.1.1", path = "../rfm9" }
w25qx = { version = "0.1.1", path = "../w25qx" }
lsm6dso-spi = { version = "0.1.1", path = "../lsm6dso-spi" }
h3lis = { version = "0.1.1", path = "../h3lis" }
uunit = { git = "https://github.com/Nautki/uunit", version = "0.1.0" }
serde = {version = "1.0.218", default-features = false }
postcard = { version = "1.1.1", default-features = false, features = ["embedded-io-06"] }
embedded-hal = "1.0.0"
defmt-rtt = "*"
embedded-io = "0.6.1"
zerocopy = { git = "https://github.com/google/zerocopy", features = ["derive"] }
byteorder = { version = "1.5.0", default-features = false }
snafu = { version = "0.8.5", default-features = false }
paste = "1.0.15"
heapless = "0.8.0"
sirin-shared = { version = "0.1.0", path = "../sirin-shared" }
