[package]
name = "w25qx"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "W25Qxx Flash Chips"
repository = "https://github.com/Nautki/sirin"

[dependencies]
embedded-hal-async = "1.0.0"
spi-handle = { version = "0.1.1", path = "../spi-handle" }

[dev-dependencies]
tokio = { version = "1.49.0", features = ["rt", "macros"] }
