[package]
name = "sirin-filter"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Kalman filter for sirin written in rust"
repository = "https://github.com/Nautki/sirin"

[dependencies]
nalgebra = { version = "0.34.1", default-features = false, features = ["libm"] }
libm = "0.2"
defmt = "*"