[package]
name = "lis3mdl"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Lis3mdl Magnetometer"
repository = "https://github.com/Nautki/sirin"

[dependencies]
dev-csr = { version = "0.1.1", path = "../dev-csr" }
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
spi-handle = { version = "0.1.1", path = "../spi-handle" }
