[package]
name = "sirin-macros"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Macros for Sirin"
repository = "https://github.com/Nautki/sirin"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
syn = { version = "2.0.100", features = ["extra-traits", "full"] }
proc-macro2 = "1.0.94"