[package]
name = "sirin-c"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "C portion of code for Sirin"
repository = "https://github.com/Nautki/sirin"
include = ['src/sirin-c.c']

[dependencies]
libc = { version = "0.2.169", features = [] }

[build-dependencies]
cc = "1.2"
walkdir = "2.5.0"
